### ISSUE TITLE
Cambio de servidor api.labcd.mx

### ISSUE THREAD

**Issue by paulinabustos** [LabPLC/api.labcd.mx#50]
@mikesaurio ¿puedes revisar los detalles de este cambio con @ayouidaniel?

**Comment by mikesaurio** [comment]
@paulinabustos ya le pedí a @ayouidaniel los detalles de este cambio

**Comment by paulinabustos** [comment]
Perfecto, @mikesaurio ¿te puedo apoyar en algo?

**Comment by tellodaniel** [comment]
Si quedó claro? @mikesaurio
