### ISSUE TITLE
Cambio de contenido

### ISSUE THREAD

**Issue by paulinabustos** [LabPLC/api.labcd.mx#51]
Cambiar
APIS DE LA CIUDAD DE MÉXICO
API DE MOVILIDAD
Contiene los métodos para obtener información relevante a la movilidad en el Distrito Federal
por
API DE LA CIUDAD DE MÉXICO
API DE MOVILIDAD
Contiene los métodos para obtener información relevante a la movilidad en la Ciudad de México

**Comment by mikesaurio** [comment]
http://datos.labcd.mx/apis @poguez  este creo que sería más rápido si lo cambias directamente tu? abrazo. :)

**Comment by poguez** [comment]
true :heavy_check_mark:

**Comment by zoek1** [comment]
Movido al repositorio del [Laboratorio de datos](https://github.com/LabPLC/Laboratorio-de-datos/issues/33)
