### ISSUE TITLE
Placas de otros estados y nuevas mandan error en API de corralones

### ISSUE THREAD

**Issue by ChaconC** [LabPLC/api.labcd.mx#55]
Las placas con el nuevo estilo, las de otros estados y las de taxi mandan error de placa inválida al consultar el estatus de corralon.

En este PR se hace compatible el regex para validar estas placas
https://github.com/LabPLC/api.labcd.mx/pull/54

**Comment by mikesaurio** [comment]
Gracias @ChaconC  revisando y haciendo Merge
