### ISSUE TITLE
End Point de Registro civil

### ISSUE THREAD

**Issue by mikesaurio** [LabPLC/api.labcd.mx#57]
Regresa siempre: 
SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://10.39.1.101/FestivalDatos/index.php?

No se puede acceder

**Comment by paulinabustos** [comment]
@ayouidaniel ¿nos puedes apoyar con esto?

**Comment by tellodaniel** [comment]
Lo reviso

**Comment by mikesaurio** [comment]
No se tiene acceso a la API.
Se decide concluir ya que no logramos tener acceso.
