### ISSUE TITLE
End Point de PGJ

### ISSUE THREAD

**Issue by mikesaurio** [LabPLC/api.labcd.mx#58]
Se obtiene este error al quererlo consumir Operation timed out - connect(2) for "172.19.80.208" port 80

**Comment by paulinabustos** [comment]
@ayouidaniel ¿nos puedes apoyar con esto?

**Comment by tellodaniel** [comment]
Lo reviso

**Comment by mikesaurio** [comment]
No se tiene acceso a la API.
Se decide concluir ya que no logramos tener acceso.
