### ISSUE TITLE
EndPoint de Automóviles DF

### ISSUE THREAD

**Issue by mikesaurio** [LabPLC/api.labcd.mx#59]
El código de acceso a la API realizada por Manuel está en PHP y en su carpeta personal, no tengo acceso a ella, es por eso que se optó por poner un espejo y guardar en un cache en nuestro servidor esta información, ademas que este no solo conecta con SEDEMA sino también con FINANZAS.

**Comment by paulinabustos** [comment]
@ayouidaniel ¿nos apoyas con esto?

**Comment by mikesaurio** [comment]
Se resuelve conflicto! de este tipo
http://datos.labplc.mx/movilidad/vehiculos/Z66ACT.json
http://api.labcd.mx/v1/movilidad/vehiculos/Z66ACT

**Comment by mikesaurio** [comment]
La API que esta en http://datos.labplc.mx/movilidad/vehiculos/819utt.json consume de 3 lados:
1.- Historial de verificaciones: Consume de un WS que está en la carpeta de Manuel Rabade en PHP, se requeriría pasar a Rails.
2.- Historial de Tenencias: Este no es una API es un Scraping a la pagina de  http://www.finanzas.df.gob.mx/ por lo que se perderia la funcionalidad.
3.- Historial de Infracciones: Este EndPoint fue realizado por Carlos y la IP está casada con otro dominio, tenemos que pedirle su WS para poder pasarlo a RAILS y dar de alta la ip nueva o se perderá la funcionalidad.

**Comment by mikesaurio** [comment]
Este issue se cierra con los cambios realizados a la expresión  regular de placas, el problema de cambiar la API se  englobara en https://github.com/LabPLC/api.labcd.mx/issues/62
