### ISSUE TITLE
Corrección del análisis en el código de placas en el API de vehículo

### ISSUE THREAD

**Issue by paulinabustos** [LabPLC/api.labcd.mx#65]

**Comment by paulinabustos** [comment]
@zoek1 @mikesaurio - ¿qué implica resolver este issue?

**Comment by paulinabustos** [comment]
Hablando con @zoek1 este issue ya está resuelto.

**Comment by paulinabustos** [comment]
Hablando con @zoek1 este issue ya está resuelto.

**Comment by paulinabustos** [comment]
Hablando con @zoek1 este issue ya está resuelto.

**Comment by paulinabustos** [comment]
Hablando con @zoek1 este issue ya está resuelto.

**Comment by paulinabustos** [comment]
Hablando con @zoek1 este issue ya está resuelto.

**Comment by paulinabustos** [comment]
Lo cerraremos después de hacer la prueba con el Servidor de placas arriba. 

¿Nos avisas @ayouidaniel?

**Comment by tellodaniel** [comment]
datos.labplc.mx ya está arriba.

**Comment by paulinabustos** [comment]
@zoek1 ¿lo probamos?

**Comment by paulinabustos** [comment]
Este issue está cerrado, abriremos otro con el problema de verificaciones.
