### ISSUE TITLE
Typo en ecobici example

### ISSUE THREAD

**Issue by ropa03** [LabPLC/api.labcd.mx#66]
Hola,

tienen está URL mal, falta la i en ecobici:

api.labcd.mx/v1/movilidad/estaciones-ecobic/3

El json de respuesta no incluye las bicis disponibes y slots:

"status":null,"bikes":null,"slots":null

¿Pueden ayudarme para obtener las bicis de cada estación?

Gracias

**Comment by paulinabustos** [comment]
Gracias @ropa03. Lo revisamos y te enviamos una respuesta.
