### ISSUE TITLE
API Vehiculos LABCDMX

### ISSUE THREAD

**Issue by oxcar** [LabPLC/api.labcd.mx#67]
Buenas,

El API de vehículos de LABCDMX no está funcionando correctamente.
http://api.labcd.mx/v1/movilidad/vehiculos/989YDK

Sin embargo el API de LABPLC si regresa resultados (aunque no de verificaciones)
http://datos.labplc.mx/movilidad/vehiculos/989YDK.json

¿Cual es la versión más actualizada?

**Comment by oxcar** [comment]
Parece ser que ya resucitó.

**Comment by paulinabustos** [comment]
Gracias por el issue @oxcarh, avísanos si encuentras algún otro problema.
