### ISSUE TITLE
API de vehículos no devuelve las Verificaciones

### ISSUE THREAD

**Issue by paulinabustos** [LabPLC/api.labcd.mx#68]
Las verificaciones de los vehículos no se muestran y las verificaciones aparecen vacías. 

api.labcd.mx/v1/movilidad/vehiculos/111MMM

Diagnóstico: El error ocurre porque no se reconocen las dependencias de PHP, en específico la extensión que debe procesar la base de datos.

**Comment by zoek1** [comment]
Además del error de dependencia que se resolvio, se inválido la caché existente. Esto debido a que si una clave no era válido se enviaba un error en vez de actualizarlo con el valor correcto.
