### ISSUE TITLE
Base de datos (Taxis) datos incorrectos

### ISSUE THREAD

**Issue by rud0lph09** [LabPLC/api.labcd.mx#70]
Sali a la calle a tomar placas de taxis, un numero considerable para un test, pero para todos saca error.

Siendo mas específicos me regresa esto

`
</head>
    <body>
        
        <div class="dialog">
            <div>
                <h1>We're sorry, but something went wrong.</h1>
            </div>
            <p>If you are the application owner check the logs for more information.</p>
        </div>
    </body>
`

No tengo idea por que... Anexo la lista de placas que probe...

A69574
A81846
A90263
A38787
A74098
A59197
A41625
A24228
B31555
A39553
A24886
X05ABE - Con este me envío que las placas no eran validas. Supongo ahi si es piratón
A74679
M02675
A70973
A90814
B29739
A54709

Todos me respondió con el mismo documento html

Nota: Todas las placas fueron registradas de taxis en la calzada de Tlalpan a la altura de Taxqueña

**Comment by tellodaniel** [comment]
Actualmente la API no se encuentra en funcionamiento. El cambio de administración que sucedió en la SEMOVI provocó que nos suspendieran el servicio. Estamos en pláticas con ellos para que esto sea solucionado.

**Comment by rud0lph09** [comment]
Muchas gracias :) Pense que tendría que cancelar mi proyecto u.u pero gracias :D
