### ISSUE TITLE
¿Cual es el API oficial?

### ISSUE THREAD

**Issue by pakmans** [LabPLC/api.labcd.mx#72]
Me encontré esta (http://api.labcd.mx/v1/movilidad/vehiculos/), pero también el de http://datos.labplc.mx/movilidad/vehiculos
Las respuestas son distintas (por ejemplo infractions vs. infracciones)

**Comment by tellodaniel** [comment]
El Laboratorio de Datos es un repositorio de datasets y servicios web construidos a partir de datos facilitados por entidades de gobierno al Laboratorio para la Ciudad, estructurados por hackers cívicos. Este proyecto es un experimento por lo que no lo consideramos oficial, el único portal oficial es el que está a cargo de [Oficialía Mayor](http://www.gobiernoabierto.cdmx.gob.mx/).

La primer API que mencionas fue creado para su uso en la segunda edición de [HackCDMX](http://hack.labcd.mx) por lo que contiene la url actualizada y ciertos cambios como bien lo mencionas. La segunda url fue creada para la primera edición llamada HackDF.

Próximamente actualizaremos el portal para mejorar los datasets y servicios web. Te recomiendo que uses la primera url.

**Comment by pakmans** [comment]
Ok, gracias ... pero ¿Cómo es que la primera versión (segunda liga) tiene mejor estructura y documentación que la primera? ¿Seguro que la primera liga (o sea este proyecto) es el bueno?
Gracias.
