### ISSUE TITLE
Encoding equivocado

### ISSUE THREAD

**Issue by pakmans** [LabPLC/api.labcd.mx#73]
En los campos de texto (motivo y fundamento, específicamente) los caracteres acentuados no solo vienen codificados de manera poco ortodoxa en términos de json, sino que vienen mál codificados.
En su ejemplo (111MMM) si vienen bien (a medias...), pero en otros casos, por ejemplo 377XYZ viene:

"motivo":"VEHICULO USO PARTICULAR - LOS CONDUCTORES DE VEH**\u0026Ouml;**CULOS DEBER**\u0026micro;**N RESPETAR LOS L**\u0026Ouml;**MITES DE VELOCIDAD ESTABLECIDOS EN LA SE**\u0026yen;**ALIZACI**\u0026agrave;**N VIAL. A FALTA DE SE**\u0026yen;**ALAMIENTO RESTRICTIVO ESPEC\u0026Ouml;FICO, LOS L**\u0026Ouml;**MITES DE VELOCIDAD SE ESTABLECER**\u0026micro;**N DE ACUERDO A LO SIGUIENTE: EN V**\u0026Ouml;**AS PRIMARIAS LA VELOCIDAD M**\u0026micro;**XIMA SER**\u0026micro;** DE 50 KIL**\u0026agrave;**METROS POR HORA;"

Como se puede ver, la primera aparición viene VEH**\u0026Ouml;**CULOS, dónde \u0026Ouml; es un híbrido que se traduciría a una entidad de HTML &Ouml; que representa una O mayúscula con diéresis, en lugar de una I mayúscula con acento.

Es decir, hay 3 problemas:
1. Siendo JSON debería de venir tal cual la letra acentuada en UTF-8 según el punto 8.1 del estándar:
   
   > JSON text SHALL be encoded in UTF-8, UTF-16, or UTF-32.  The default
   > encoding is UTF-8
   > [https://tools.ietf.org/html/rfc7159#section-8.1](url)
2. Concediendo que viniera como una entidad de HTML, debería venir como &Iacute; y no como \u0026Iacute;  Si van a utilizar el escaping de unicode (\u) por que no codificar entonces el caracter que se quiere representar directamente (\u00cf para la i mayúscula con acento) en lugar de "escapear" el caracter &
3. Aún concediendo que venga mal, según los puntos anteriores, ni siquiera es correcto porque en lugar de venir I mayúscula con acento viene O con diéresis.

**Comment by tellodaniel** [comment]
Coincido contigo el problema es que la información que consumimos viene mal codificada de origen. Nosotros no somos responsables de la información, los responsables son finanzas. De hecho si te vas a su sitio web ellos muestran la misma información mal codificada. 

Estamos trabajando con ellos para ver la manera en que los solucionaremos.
