### ISSUE TITLE
No funciona el detalle de la estación de Ecobici

### ISSUE THREAD

**Issue by jokame** [LabPLC/api.labcd.mx#75]
Funciona bien la API para obtener la lista de estaciones de Ecobici, pero cuando se solicita el detalle de una estación se presenta un error.

No hay más información y sólo aparece una leyenda de que se consulte el log de la aplicación.

**Comment by tellodaniel** [comment]
Estamos trabajando para sacar una segunda versión de las APIs mientras tanto te recomiendo consultar directamente de la fuente:  https://www.ecobici.df.gob.mx/es/informacion-del-servicio/open-data
